### ISSUE TITLE
Returned dialogs list is not accurate in two ways, help needed!

### ISSUE THREAD

**Issue by RenaZhou** [QuickBlox/q-municate-ios#129]
By using this method: [ServicesManager.instance.chatService.dialogsMemoryStorage dialogsSortByUpdatedAtWithAscending:NO], we expect to get all the dialogs the current user is in, but the returned dialogs list is not accurate in two ways:

1. It lost some dialogs, and we're sure data limit of 'page' parameter is not the reason here;
2. It still returns the dialogs where the user has already left.

Could you please help have a check? Or is there some other way to get the correct dialogs list?

Thank you very much.

====================== Source Code ======================
{
// Retrieving dialogs sorted by updatedAt date from memory storage.
return [ServicesManager.instance.chatService.dialogsMemoryStorage dialogsSortByUpdatedAtWithAscending:NO];
}
====================== Source Code ======================

**Comment by Raikerian** [comment]
Hi @RenaZhou 

Q-municate does not have ServicesManager singleton class. I guess your problem is related to our samples: https://github.com/QuickBlox/quickblox-ios-sdk
However I need more information from you in order to help you solve your problem (as we do not have such problem in our samples). Please provide us full logs from from app start till the issue occurs.

**Comment by Raikerian** [comment]
@RenaZhou 

any updates for this?

**Comment by RenaZhou** [comment]
Hello @Raikerian ,

Thank you so much for your response on this, and sorry for getting back late. According to what you said that samples don't have the issue, we re-installed the SDK and the issue is gone.

Let me close this issue and thank you for your help again. :)
